#' patch data
#'
#' Patch data with a diff generated by \code{\link{diff_data}}
#'@param data \code{data.frame} that should be patched
#'@param patch generated with diff_data
#'@return \code{data.frame} that has been patched.
#'@export
patch_data <- function(data, patch){
  stopifnot(inherits(patch, "TableView"))
  ctx <- patch$ctx
  mode <- patch$mode

  tv <- TableView(ctx, data)
  ctx$call("patch_data", I(tv$var_name), I(patch$var_name))
  data <- tv$get_data()

  for (n in names(data)){
    mode(data[[n]]) <- mode[n]
  }
  data
}
